juegotruco/juegotruco/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^truco/', include('truco.urls', namespace="truco")),
    url(r'^usuarios/', include('usuarios.urls', namespace="usuarios")),
)

juegotruco/truco/urls.py
from django.conf.urls import patterns, url

from truco import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^lobby$', views.lobby, name='lobby'),
    url(r'^crear_partida$', views.crear_partida, name='crear_partida'),
    url(r'^unirse_partida$', views.unirse_partida, name='unirse_partida'),
    url(r'^partida/(?P<partida_id>\d+)$', views.partida, name='partida'),
    url(r'^en_espera/(?P<partida_id>\d+)$', views.en_espera, name='en_espera'),
    url(r'^fin_de_ronda/(?P<partida_id>\d+)$', views.fin_de_ronda, name='fin_de_ronda'),
    url(r'^ronda/(?P<partida_id>\d+)$', views.ronda, name='ronda'),
    url(r'^tirar_carta/(?P<partida_id>\d+)/(?P<carta_id>\d+)$', views.tirar_carta, name='tirar_carta'),
    url(r'^responder_canto/(?P<partida_id>\d+)/(?P<opcion>\d+)$', views.responder_canto, name='responder_canto'),
)

juegotruco/truco/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from truco.constants import *


class LoginForm(forms.Form):
    username = forms.CharField(max_length=255, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)


class RegisterForm(UserCreationForm):
# Personalizamos la clase UserCreationForm
    email = forms.CharField(max_length=255, required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class crear_partida_form(forms.Form):
    nombre = forms.CharField(max_length=32, required=True)
    puntos_objetivo = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PUNTOS_OBJETIVO, required=True
        )
    cantidad_jugadores = forms.ChoiceField(
        widget=forms.RadioSelect, choices=CANTIDAD_JUGADORES, required=True
        )

juegotruco/truco/views.py
from django.shortcuts import render, redirect
from django.template import RequestContext, loader, Context
from django.template.response import TemplateResponse
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from truco.models import Lobby, Partida, Jugador, Carta, Ronda
from truco.constants import *
from truco.forms import crear_partida_form
from truco.views_helper import *
from django.dispatch import receiver


"""
View Lobby: Se muestran las partidas donde aun hay lugar para mas jugadores.
"""
@login_required(login_url='/usuarios/login')    
def lobby(request):
    lobby = Lobby()
    lista_de_partidas = lobby.get_lista_partidas()
    context = {
        'lista_de_partidas': lista_de_partidas,
        'username': request.user.username
        }
    return render(request, 'truco/lobby.html', context)


"""
View index: Es la unica view de la aplicacion truco que puede accederse sin estar
logueado, caso en el cual redirecciona al login. Si el usuario esta logueado lo
redirige al lobby.
"""
def index(request):
        # Si esta logueado entra al lobby directamente
        return redirect(reverse('truco:lobby'))


"""
View crear una partida: muestra el formulario para crear una nueva partida.
Los campos nombre y puntos objetivo son obligatorios. El campo password es opcional.
"""
@login_required(login_url='/usuarios/login')
def crear_partida(request):
    if request.method == "POST":
        form = crear_partida_form(data=request.POST)
        if form.is_valid():
            # Si se llenaron los campos obligatorios
            lobby = Lobby()
            partida = lobby.crear_partida(
                request.user,
                form.cleaned_data['nombre'],
                form.cleaned_data['puntos_objetivo'],
                form.cleaned_data['cantidad_jugadores']
                )
            return redirect(reverse('truco:partida', args=(partida.id, )))
        else:
            # Si el formulario es incorrecto se muestran los errores
            return render(request, 'truco/crear_partida.html', {'form': form})
    else:
        # SI hay un GET se muestra el formulario para crear partida
        form = crear_partida_form()
        return render(request, 'truco/crear_partida.html', {'form': form})


"""
View unirse a una partida: Si se selecciona una partida a la que se puede ingresar,
se redirige al usuario a la partida en la vista "en espera". Si no, si lo vuelve al lobby.
El usuario no puede ingresar a una partida si no selecciono una partida de la lista
que se muestra en el lobby o si ya tiene un jugador en la partida que eligio.
"""
@login_required(login_url='/usuarios/login')
def unirse_partida(request):
    partida = request.POST.get('partida', False)
    if partida:
        lobby = Lobby()
        partida = Partida.objects.get(pk=request.POST['partida'])
        if lobby.unirse_partida(request.user, partida) == -1:
            # Si no puedo unirme a la partida
            return redirect(reverse('truco:lobby'))
        else:
            # Si selecciona una partida a la que puede ingresar
            partida.actualizar_estado()
            return redirect(reverse('truco:en_espera', args=(partida.id, )))
    else:
        # No se selecciono una partida
        return redirect(reverse('truco:lobby'))


"""
View partida: Se encarga de definir cuando la partida debe continuar o terminar.
Si no se termina, crea una nueva ronda, de lo contrario, te muestra el html partida
"""
@login_required(login_url='/usuarios/login')
def partida(request, partida_id):
    partida = Partida.objects.get(pk=partida_id)
    if partida:
        # La partida existe
        if partida.get_ganador() < 0:
            # No hay un ganador de la partida
            partida.actualizar_puntajes()
        if partida.is_ready():
            # Si no hay una ronda en curso y los jugadores estan listos
            ronda = partida.crear_ronda()
            partida.actualizar_mano()  # Se le da la mano al jugador de la derecha
            return redirect(reverse('truco:en_espera', args=(partida.id, )))
        else:
            context = {
                'partida': partida,
                'puntajes': partida.get_puntajes(request.user),
                'username': request.user.username,
                'mensaje_ganador': partida.get_mensaje_ganador(request.user)
                }
            return render(request, 'truco/partida.html', context)
    else:
        return redirect(reverse('truco:index'))


"""
View en espera: Se redirigen los jugadores a esta vista cuando no es su turno.
Aqui solo se puede ver las cartas propias, las ya jugadas en la mesa y el mensaje
del resultado del envido.
"""
@login_required(login_url='/usuarios/login')
def en_espera(request, partida_id):
    partida = Partida.objects.get(pk=partida_id)
    ronda = partida.get_ronda_actual()
    jugador = partida.find_jugador(request.user)  # jugador del usuario
    if partida.get_ganador() >= 0:
        return redirect(reverse('truco:partida', args=(partida_id, )))
    elif ronda and jugador == ronda.get_turno():
        # Si hay una ronda en curso y es el turno del jugador
        return redirect(reverse('truco:ronda', args=(partida_id, )))
    else:
        context = Context({
            'puntajes': partida.get_puntajes(request.user),
            'partida': partida,
            'username': request.user.username
            })
        if ronda:
            context['cartas_disponibles'] = jugador.get_cartas_disponibles()
            context['cartas_jugadas'] = lista_cartas_jugadores(ronda.get_cartas_jugadas(jugador))
            context['cant_cartas_adversario'] = lista_cantidad_cartas(ronda.cant_cartas_adversario(jugador))
            context['nombre_jugadores'] = lista_nombres_jugadores(ronda.nombres_jugadores(jugador))
            if not ronda.hay_ganador():
                context['mensaje_envido'] = ronda.get_mensaje_ganador_envido(jugador)
                context['mensaje_canto'] = ronda.get_mensaje_canto(jugador)
                context['mensaje_puntos_cantados'] = ronda.get_mensaje_puntos_cantados()
                context['jugador_en_turno'] = ronda.get_turno().nombre
            if ronda.hay_que_mostrar_los_puntos():
                context['cartas_a_mostrar'] = ronda.ultimo_envido().get_puntos_a_mostrar()
        return render(request, 'truco/en_espera.html', context)


"""
View ronda: Se muestran las opciones de juego que tiene un jugador en turno.
Se evalua la opcion elegida y se redirige al jugador a la view "en espera"
si canta, a la view responder canto si hay un canto no respondido y a la view tirar
carta si eligio tirar una carta. Si hay un ganador, se lo redirige a la partida.
"""
@login_required(login_url='/usuarios/login')
def ronda(request, partida_id):
    partida = Partida.objects.get(pk=partida_id)
    ronda = partida.get_ronda_actual()
    jugador = partida.find_jugador(request.user)
    if request.method == "POST":
        # El jugador eligio una opcion
        if 'puntos_cantados' in request.POST:
            if puntos_cantados_validos(request.POST['puntos_cantados'], ronda, jugador):
                return redirect(reverse('truco:en_espera', args=(partida.id, )))
            else:
                return redirect(reverse('truco:ronda', args=(partida_id, )))
        if 'opcion' in request.POST:
            opcion = int(request.POST['opcion'])
            if (respuestas_a_cantos(ronda, opcion)):
                return redirect(reverse('truco:responder_canto', args=(partida.id, opcion, )))
            elif opcion == IRSE_AL_MAZO:
                ronda.irse_al_mazo(jugador)
                return redirect(reverse('truco:en_espera', args=(partida.id,)))
            elif opcion == SON_BUENAS:
                set_perdedor_envido(ronda, jugador)
                return redirect(reverse('truco:en_espera', args=(partida.id, )))
            elif nuevo_canto(opcion):
                # Hay un canto inicial
                puntos_restantes = partida.get_min_pts_restantes()
                ronda.crear_canto(opcion, jugador, puntos_restantes)
                return redirect(reverse('truco:en_espera', args=(partida.id,)))
        elif 'carta' in request.POST:
            # Jugar una carta
            return redirect(reverse('truco:tirar_carta', args=(partida.id, request.POST['carta'],)))
    else:
        if not ronda.hay_ganador():
            # Si no se termino la ronda muestra las opciones
            context = {
                'puntajes': partida.get_puntajes(request.user),
                'partida': partida,
                'username': request.user.username,
                'cartas_disponibles': jugador.get_cartas_disponibles(),
                'cartas_jugadas': lista_cartas_jugadores(ronda.get_cartas_jugadas(jugador)),
                'cant_cartas_adversario' : lista_cantidad_cartas(ronda.cant_cartas_adversario(jugador)),
                'opciones': ronda.get_opciones(),
                'op_dict': OPCIONES,
                'mensaje_envido': ronda.get_mensaje_ganador_envido(jugador),
                'mensaje_canto' : ronda.get_mensaje_canto(jugador),
                'mensaje_puntos_cantados' : ronda.get_mensaje_puntos_cantados(),
                'puede_tirar_carta': ronda.se_puede_tirar(),
                'cantar_puntos': ronda.se_debe_cantar_puntos(),
                'nombre_jugadores': lista_nombres_jugadores(ronda.nombres_jugadores(jugador))
                }
            return render(request, 'truco/ronda.html', context)
        else:  # Se termino la ronda
            return redirect(reverse('truco:fin_de_ronda', args=(partida.id, )))


"""
View tirar carta: Maneja el caso donde la opcion elegida por el jugador en turno
(view ronda) elige tirar una carta. Si no se termino la ronda, se crea un nuevo

juegotruco/truco/templates/truco/crear_partida.html
<!DOCTYPE html>
<html>
    <head>
        <title> Crear Partida </title>
    </head>

    <body background="https://mauricioyanes.files.wordpress.com/2011/03/naipes-copy.jpg">
        <div style="background-color:#424242;
                    border: 2px dashed black;
                    border-radius: 10px;
                    width:400px;
                    margin-left:35%;">
            <form action="" method="POST" style="color:white; font-size:20px; margin-left:5px;">
                <h3 style="font-family:cursive; text-align:center;">Creación de Partida</h3>
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit" style="border-radius:3px;display:inline-block;margin-left:24%;margin-bottom:5%;">Crear nueva partida</button>
            </form>
        </div>
    <body>

</html>

juegotruco/truco/templates/truco/en_espera.html
<!DOCTYPE html>
{% extends "truco/partida.html" %}
{% load staticfiles %}
<html>
    <head>
        <title> Ronda </title>
    </head>

    <body>
    {% block mensajes%}
        <div id="cuadro_mensaje_ganador_envido">
            {{mensaje_envido}}
        </div>
        <div id="cuadro_cantos_respuestas">
            {{mensaje_canto}}
        </div>
        <div id="cuadro_puntos_cantados">
            {{mensaje_puntos_cantados}}
        </div>
        <div id="cuadro_turno">
            {% if jugador_en_turno %}
                El turno es de {{jugador_en_turno}}
            {% endif %}
        </div>
    {% endblock mensajes %}
    {% block pantalla_de_juego %}
        {% if cartas_a_mostrar %}
        <div id="cartas_conforman_puntos">
                {% for carta in cartas_a_mostrar %}
                    <img src={% static "truco/images/" %}{{carta}}/>
                {% endfor %}
        </div>
        {% endif %}
        <div id="par_de_jugadores_uno">
            <div id="jugador_arriba">
                <div id="nombre_jugador">
                    {{nombre_jugadores.5}}
                </div>
                <div id="cuadro_cartas_arriba">
                    {% for i in cant_cartas_adversario.4 %}
                        <img src={% static "truco/images/cartas/naipe.jpg"%}/>
                    {% endfor %}
                </div>
                <div class="cuadro_cartas_tiradas">
                    {% for carta in cartas_jugadas.5 %}
                        {% if forloop.counter == 1 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="primera_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 2 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="segunda_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 3 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="tercera_imagen"/>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>

            <div id="jugador_abajo">
                <div class="cuadro_cartas_tiradas">
                    {% for carta in cartas_jugadas.0 %}
                        {% if forloop.counter == 1 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="primera_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 2 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="segunda_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 3 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="tercera_imagen"/>
                        {% endif %}
                    {% endfor %}
                </div>

                <div id="cuadro_cartas_abajo">
                    {% for carta in cartas_disponibles %}
                        <img src={% static "truco/images/"%}{{carta}}/>
                    {% endfor %}
                </div>
                <div id="nombre_jugador">
                    {{nombre_jugadores.0}}
                </div>
            </div>
        </div>

        <div id="par_de_jugadores_dos">
            <div id="jugador_arriba">
                <div id="nombre_jugador">
                    {{nombre_jugadores.4}}
                </div>
                <div id="cuadro_cartas_arriba">
                    {% for i in cant_cartas_adversario.3 %}
                        <img src={% static "truco/images/cartas/naipe.jpg"%}/>
                    {% endfor %}
                </div>

                <div class="cuadro_cartas_tiradas">
                    {% for carta in cartas_jugadas.4 %}
                        {% if forloop.counter == 1 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="primera_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 2 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="segunda_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 3 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="tercera_imagen"/>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div id="jugador_abajo">
                <div class="cuadro_cartas_tiradas">
                    {% for carta in cartas_jugadas.1 %}
                        {% if forloop.counter == 1 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="primera_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 2 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="segunda_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 3 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="tercera_imagen"/>
                        {% endif %}
                    {% endfor %}
                </div>
                <div id="cuadro_cartas_abajo">
                    {% for i in cant_cartas_adversario.0 %}
                        <img src={% static "truco/images/cartas/naipe.jpg"%}/>
                    {% endfor %}
                </div>
                <div id="nombre_jugador">
                    {{nombre_jugadores.1}}
                </div>
            </div>
        </div>

        <div id="par_de_jugadores_tres">
            <div id="jugador_arriba">
                <div id="nombre_jugador">
                    {{nombre_jugadores.3}}
                </div>
                <div id="cuadro_cartas_arriba">
                    {% for i in cant_cartas_adversario.2 %}
                        <img src={% static "truco/images/cartas/naipe.jpg"%}/>
                    {% endfor %}
                </div>

                <div class="cuadro_cartas_tiradas">
                    {% for carta in cartas_jugadas.3 %}
                        {% if forloop.counter == 1 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="primera_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 2 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="segunda_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 3 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="tercera_imagen"/>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div id="jugador_abajo">
                <div class="cuadro_cartas_tiradas">
                    {% for carta in cartas_jugadas.2 %}
                        {% if forloop.counter == 1 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="primera_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 2 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="segunda_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 3 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="tercera_imagen"/>
                        {% endif %}
                    {% endfor %}
                </div>
                <div id="cuadro_cartas_abajo">
                    {% for i in cant_cartas_adversario.1 %}
                        <img src={% static "truco/images/cartas/naipe.jpg"%}/>
                    {% endfor %}
                </div>
                <div id="nombre_jugador">
                    {{nombre_jugadores.2}}
                </div>
            </div>
        </div>
    {% endblock pantalla_de_juego %}
    </body>
</html>

juegotruco/truco/templates/truco/fin_de_ronda.html
<!DOCTYPE html>
<html>
    {% extends "truco/partida.html" %}
    {% load staticfiles %}
    {% load custom_filters %}
    <head>
        <title> Ronda </title>
        {% block refresh %}
        {% endblock refresh %}
    </head>

    <body>
        {% load staticfiles %}
        <div id="barra_arriba">
                <h4>Bienvenido {{ username }}</h4>
                <h5>PARTIDA {{ partida }}</h5>
                <button type="submit"><a href="/truco/lobby">Retirarse</a></button>
        </div>

        <div id ="puntajes">
            <table>
                <tr>
                    <td>Mi equipo</td>
                    <td>Otro equipo</td>
                </tr>
                <tr>
                    <td>{{ puntajes.0 }}</td>
                    <td>{{ puntajes.1 }}</td>
                </tr>
            </table>
        </div>

        {% block mensajes %}
        <div id="cuadro_botones_fin_ronda">
            {% for opcion in opciones %}
                <form id="form_opciones" action="{% url 'truco:fin_de_ronda' partida.id %}" method="post">
                {% csrf_token %}
                {% if opcion == 11 %}
                    <input type="image" class="btTxt submit" style="height:130px;width:130px" name="opcion" value="{{ opcion }}" src={% static "truco/images/siguiente_ronda.png" %} />
                {% else %}
                    <div id="botones_opciones_chicos">
                        <button type="submit" name="opcion" value="{{ opcion }}" style=""> {{ op_dict|get_item:opcion}}</button>
                    </div>
                {% endif %}
            </form>
            {% endfor %}
        </div>
        {% endblock mensajes%}
        {% block pantalla_de_juego %}
        <div id="cartas_conforman_puntos">
            {% if cartas_a_mostrar %}
                {% for carta in cartas_a_mostrar %}
                    <img src={% static "truco/images/" %}{{carta}}/>
                {% endfor %}
            {% endif %}
        </div>
        <div id="par_de_jugadores_uno">
            <div id="jugador_arriba">
                <div id="nombre_jugador">
                    {{nombre_jugadores.5}}
                </div>
                <div id="cuadro_cartas_arriba">
                    {% for i in cant_cartas_adversario.4 %}
                        <img src={% static "truco/images/cartas/naipe.jpg"%}/>
                    {% endfor %}
                </div>
                <div class="cuadro_cartas_tiradas">
                    {% for carta in cartas_jugadas.5 %}
                        {% if forloop.counter == 1 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="primera_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 2 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="segunda_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 3 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="tercera_imagen"/>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div id="jugador_abajo">
                <div class="cuadro_cartas_tiradas">
                    {% for carta in cartas_jugadas.0 %}
                        {% if forloop.counter == 1 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="primera_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 2 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="segunda_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 3 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="tercera_imagen"/>
                        {% endif %}
                    {% endfor %}
                </div>
                <div id="cuadro_cartas_abajo">
                    {% if puede_tirar_carta %}
                        {% for carta in cartas_disponibles %}
                        <form method="post">
                        {% csrf_token %}
                            <button type="submit" name="carta" value="{{carta.id}}" style=""><img src={% static "truco/images/"%}{{carta}}/></button>
                        </form>
                        {% endfor %}
                    {% else %}
                        {% for carta in cartas_disponibles %}
                            <img src={% static "truco/images/"%}{{carta}}/>
                        {% endfor %}
                    {%endif%}
                </div>
                <div id="nombre_jugador">
                    {{nombre_jugadores.0}}
                </div>
            </div>
        </div>

        <div id="par_de_jugadores_dos">
            <div id="jugador_arriba">
                <div id="nombre_jugador">
                {{nombre_jugadores.4}}
                </div>
                <div id="cuadro_cartas_arriba">
                    {% for i in cant_cartas_adversario.3 %}
                        <img src={% static "truco/images/cartas/naipe.jpg"%}/>
                    {% endfor %}
                </div>

                <div class="cuadro_cartas_tiradas">
                    {% for carta in cartas_jugadas.4 %}
                        {% if forloop.counter == 1 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="primera_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 2 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="segunda_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 3 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="tercera_imagen"/>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div id="jugador_abajo">
                <div class="cuadro_cartas_tiradas">
                    {% for carta in cartas_jugadas.1 %}
                        {% if forloop.counter == 1 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="primera_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 2 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="segunda_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 3 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="tercera_imagen"/>
                        {% endif %}
                    {% endfor %}
                </div>
                <div id="cuadro_cartas_abajo">
                    {% for i in cant_cartas_adversario.0 %}
                        <img src={% static "truco/images/cartas/naipe.jpg"%}/>
                    {% endfor %}
                </div>
                <div id="nombre_jugador">
                {{nombre_jugadores.1}}
                </div>
            </div>
        </div>

        <div id="par_de_jugadores_tres">
            <div id="jugador_arriba">
                <div id="nombre_jugador">
                    {{nombre_jugadores.3}}
                </div>
                <div id="cuadro_cartas_arriba">
                    {% for i in cant_cartas_adversario.2 %}
                        <img src={% static "truco/images/cartas/naipe.jpg"%}/>
                    {% endfor %}
                </div>

                <div class="cuadro_cartas_tiradas">
                    {% for carta in cartas_jugadas.3 %}
                        {% if forloop.counter == 1 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="primera_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 2 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="segunda_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 3 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="tercera_imagen"/>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div id="jugador_abajo">
                <div class="cuadro_cartas_tiradas">
                    {% for carta in cartas_jugadas.2 %}
                        {% if forloop.counter == 1 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="primera_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 2 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="segunda_imagen"/>
                        {% endif %}
                        {% if forloop.counter == 3 %}
                            <img src={% static "truco/images/"%}{{carta}} id ="tercera_imagen"/>
                        {% endif %}
                    {% endfor %}
                </div>
                <div id="cuadro_cartas_abajo">
                    {% for i in cant_cartas_adversario.1 %}
                        <img src={% static "truco/images/cartas/naipe.jpg"%}/>
                    {% endfor %}
                </div>
                <div id="nombre_jugador">
                    {{nombre_jugadores.2}}
                </div>
            </div>
        </div>
        {% endblock pantalla_de_juego %}
</html>

juegotruco/truco/templates/truco/lobby.html
<!DOCTYPE html>
<html>
    {% load staticfiles %}
    <head>
        <link rel="stylesheet" href= {% static "style_lobby.css" %}>
        <title> Lobby Truco </title>
    </head>

    <body>
    <meta http-equiv="refresh" content="8">
        <div id="barra_arriba">
                <h4>Welcome {{ username }}</h4>
                <h5>TRUCO</h5>
                <button type='button'><a href="/usuarios/logout">Logout</a></button>
        </div>

        <div id="pantalla_medio">
            <form action="{% url 'truco:unirse_partida' %}" method="post">
            {% csrf_token %}
                {% for partida in lista_de_partidas %}
                    <input type="radio" name="partida" id="partida{{ forloop.counter }}" value="{{ partida.id }}" />
                    <label for="partida{{ forloop.counter }}">{{ partida }}({{ partida.cantidad_jugadores }})</label><br />
                {% endfor %}
                <input type="submit" value="Unirse a Partida" />
            </form>
            <button type="submit"'><a href="/truco/crear_partida"> Crear Partida</a></button>
        </div>
    </body>
</html>